language: c
before_install: sudo apt-get update
install: sudo apt-get install gfortran libsundials-serial-dev liblapack-dev python-numpy texlive
script: ./bootstrap && ./configure CC=gcc FC=gfortran && make && make check && make pdf
